# Generated by Django 3.2 on 2022-01-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture.category'),
        ),
    ]
